### ISSUE TITLE
When I press the "send to txt2img" button, an error appears

### ISSUE THREAD

**Issue by cr1ma** [imrayya/stable-diffusion-webui-Prompt_Generator#12]
generation, everything works, but there is an error when sending. 
![image](https://user-images.githubusercontent.com/68346266/218959634-b7d1b9e0-0e47-4794-8eee-ccb397c65ecd.png)

**Comment by imrayya** [comment]
For now, the solution is to enter an integer, corresponding to the prompt you want to send to txt2img, in the `send which to prompt` field. Should be just above the button to send it to txt2img

I'll try to make a more intuitive or elegant solution in the future but for now, follow the above step.
