### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by woshixiongda** [imrayya/stable-diffusion-webui-Prompt_Generator#19]
![image](https://user-images.githubusercontent.com/73490191/234894875-1d233ef1-ea49-4d61-9875-59243d466de2.png)

Hello, I am using the integration package webui provided by others. After installing the plug-in, the UI is not displayed correctly. How to solve it?

**Comment by imrayya** [comment]
![image](https://user-images.githubusercontent.com/8998556/234994498-60a8e007-5719-49db-81c8-22eccd3e4117.png)
Do you mean the result's panel? That only shows up when you actually generate the extended prompt

**Comment by imrayya** [comment]
Stale for now, will reopen when I get more info
