### ISSUE TITLE
Feature Request: "Send to X" buttons for prompts.

### ISSUE THREAD

**Issue by midcoastal** [imrayya/stable-diffusion-webui-Prompt_Generator#20]
#19 made me think of this...

Can we please have buttons?  :-P

**Comment by imrayya** [comment]
Buttons to do what? Like what functionalities do are you thinking of?

**Comment by midcoastal** [comment]
> Buttons to do what? Like what functionalities do are you thinking of?

Sorry, fair question.

Nothing in particular.  I just want buttons.  Like...  All over!  ;-)

no no, more specifically for sending to txt or img, etc.  The "enter a number" method works fine, but I have to look, and type, and move and click my cursor, and THINK.   UGH...  It would be so much cooler if I only had to move and click my cursor, and do the other things less, yah know?

**Comment by imrayya** [comment]
Can you test it to see the changes work for you, I'm not a 100% familiar with Gradio so not that sure
