### ISSUE TITLE
results does not appear with latest automatic 1111

### ISSUE THREAD

**Issue by scenaristeur** [imrayya/stable-diffusion-webui-Prompt_Generator#24]
Hi @imrayya your extension worked pefectly, but 
since upgrading automatic1111, results and buttons are not shown, even with default theme, and no other extension, even after prompt_generator reinstall

```python: 3.10.9  •  torch: 2.0.0+cu118  •  xformers: 0.0.17  •  gradio: 3.28.1  •  commit: [5ab7f213](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ab7f213bec2f816f9c5644becb32eb72c8ffb89)  •  checkpoint: [92970aa785](https://google.com/search?q=92970aa785eb76e427847109a8f4ec6abfab36ef941f78d295d323d79f6130c9)```

Do you have an idea why ? thxs

![image](https://github.com/imrayya/stable-diffusion-webui-Prompt_Generator/assets/4020744/6ae820a8-9ea5-449f-893d-525d6fef279f)

with no other extension, 

![image](https://github.com/imrayya/stable-diffusion-webui-Prompt_Generator/assets/4020744/3d8a1877-4c5e-45bc-a544-d15cdcb9ab62)

**Comment by scenaristeur** [comment]
i've removed the root config.json and it seems to work now . 
a cool feature could be to send all the prompt generated  by prompteGenerator from batch tab  to Script/prompt from file or textbox / list of prompt inputs


![image](https://github.com/imrayya/stable-diffusion-webui-Prompt_Generator/assets/4020744/91fd824f-a723-4bed-af6f-4dcae0330cb7)

**Comment by imrayya** [comment]
Glad to hear it working now. Strange `config.json` had something to do with because I don't touch the settings file yet
That is a great idea for an improvement. Don't know how to do it, but I'll mess around with it in the next couple of days
