### ISSUE TITLE
Doesn't appear on lastest FORGE webui

### ISSUE THREAD

**Issue by ghost** [imrayya/stable-diffusion-webui-Prompt_Generator#27]
**Describe the bug**
Doesn't appear on lastest FORGE webui

**To Reproduce**
start server i guess?

**Expected behavior**
idk

**Comment by ghost** [comment]
someone fixed it here
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1358

**Comment by imrayya** [comment]
Thanks, I pushed the changes
