### ISSUE TITLE
Extremely slow model download

### ISSUE THREAD

**Issue by parsec501** [imrayya/stable-diffusion-webui-Prompt_Generator#4]
One of the models, the 304 MB large one, seems to download from a very, very slow server at 30 KBps on a 25 MBps connection. I couldn't find the part that downloads it so I don't know where it's fetched from but it would make sense to rehost it on Huggingface if the license allows for it.

**Comment by parsec501** [comment]
On a second attempt it downloaded at a reasonable speed, not sure what happened there. Nothing changed in the network config, the two attempts happened directly after another. Probably not an issue with this repo

**Comment by imrayya** [comment]
Yeah, that sounds weird, the model is hosting on Huggingface too
