### ISSUE TITLE
Blacklist not working

### ISSUE THREAD

**Issue by Ev-Bro** [imrayya/stable-diffusion-webui-Prompt_Generator#6]
This extension is so cool! Thank you for making it. I noticed the blacklist does not seem to be working. For example, I have "unreal" and "emma watson" in there, but I am still getting prompt results containing those words. I have tried restarting the app after saving the list.

**Comment by imrayya** [comment]
In the blacklist.txt, do you have each item in a new line?
```
unreal
emma watson
```

And this may sound silly, but you have ensured that the check box is ticked?

**Comment by imrayya** [comment]
Since there been no update or reply for a week, I'm going to mark this issue as stale and that it works as intended.
