### ISSUE TITLE
Does this extension download the models or does it send prompt requests to some endpoint?

### ISSUE THREAD

**Issue by illtellyoulater** [imrayya/stable-diffusion-webui-Prompt_Generator#9]
I'd appreciate if you could make this clear somewhere on the repo... does your extension download the models locally or does it make inference requests to some free-access endpoint ? 

I could read the code myself and be able to tell, but I think those who can't should also be informed about this.

**Comment by illtellyoulater** [comment]
Perfect, all clear, thanks for taking the time to clarify the details! 👍 
(I believe in the second line above you wanted to write "prompt" in place of extension 🤓)

**Comment by imrayya** [comment]
Changed, hahaha, thanks for noticing
